title: RustFest.EU
email: team@rustfest.eu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.rustfest.eu" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Page Settings
owner: "Rust Community Europe e.V."


# social stuff:
metaKeywords: "rust, conf, rustfest, rustfesteu, conference, programming language, berlin"
twitter_username: rustfest
github_username:  rustfesteu
socialImageSrcTwitter: ""
socialImageSrcFacebook: ""
